### PR TITLE
Docs/official logflare docs

### PR DESCRIPTION
**Pull request by Ziinc**
This part 1 PR adds in docusaurus docs generation for official docs. Content is imported from 2 main parts of the app, the LQL tab and the guides section. I have updated styling to match logflare colors.

Integration articles from the existing guides section will be added in a separate PR.

This PR to be merged first for setting up vercel integration.

https://user-images.githubusercontent.com/22714384/193090673-2f455b66-333f-4f2e-89e3-8d4fd7ab9802.mov

### CODE REVIEW

**Comment by chasers** [comment]
Imported as in automatically?  

You didn't want to use the `docs` repo we have?

**Comment by Ziinc** [comment]
copied and edited manually. Will replace the in-app stuff with links to the official docs page.

i think keeping docs and code separate leads to higher friction and more likelihood for them to go out of sync. Easier to make the docs edits together with the code edits in a single PR.

**Comment by chasers** [comment]
> Will replace the in-app stuff with links to the official docs page.

Like what?

**Comment by Ziinc** [comment]
Currently it is the Search page LQL tab and the Guides navbar tab

**Review by chasers — APPROVED** [review]

**Pull request merged**
