### PR TITLE
chore: use OTP 26

### PR DESCRIPTION
**Pull request by hauleth**
- chore: update Rustler to version 0.29.x
- chore: replace calls to Logger.warn with Logger.warning

### CODE REVIEW

**Comment by hauleth** [comment]
I haven't updated `.tool-versions` (as I do not use that file personally) so I do not know if it should be handled by me, or someone else can do that.

**Comment by Ziinc** [comment]
@hauleth .tool-versions would need to be bumped to otp26 as we use asdf for environment management.

**Comment by Ziinc** [comment]
would need the tool-versions changes + `mix format`

**Comment by hauleth** [comment]
It seems that there is flaky test.

**Review by Ziinc — APPROVED** [review]

**Comment by hauleth** [comment]
Finally it pass everything. Merge it and I will update #1715 on top and it will pass as well.

**Comment by chasers** [comment]
@hauleth merged!

**Pull request merged**
