### PR TITLE
Update with PhoenixOauth2Provider v0.5.1

### PR DESCRIPTION
**Pull request by danschultzer**
This should be working, but I can't test it locally 😄

### CODE REVIEW

**Comment by danschultzer** [comment]
Just a heads up; `0.5.1` was republished with a tiny change, so you may have to clean out the deps cache.

**Comment by chasers** [comment]
Will try that ... now getting on my views in dev:

```
RuntimeError at GET /oauth/authorized_applications
Resource owner was not found with :current_user assigns
```

**Comment by danschultzer** [comment]
Yeah, it should work when you clear out the phoenix_oauth2_provider dep cache.

**Comment by chasers** [comment]
HOKAY RECOMPILING EVERYTHING :)

Seriously thanks again.

**Comment by chasers** [comment]
Alrighty lets push this and see if it works.

**Comment by chasers** [comment]
Worked!

**Comment by danschultzer** [comment]
Phew, that's great!

**Pull request merged**
